# inherit_from: rubocop-todo.yml
AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

# Ruby 1.8 compatibility
HashSyntax:
  EnforcedStyle: hash_rockets

RescueModifier:
  Enabled: false
